### ISSUE TITLE
Project does not build

### ISSUE THREAD

**Issue by charlesroddie** [MyScript/interactive-ink-examples-wpf#1]
Followed the instructions.
Using "Any CPU" the projects GetStarted.Wpf-VS2017 and Demo.Wpf-VS2017 look OK. Using x86 or x64 most of the objects "do not exist in the current context".

Regardless of any choices, all of the resources are missing from the repo and therefore the project cannot be built. The entire resources folders are missing. Can you set up CI to verify that this builds please?

**Comment by jnguiavarch** [comment]
The recognition assets URLs were bad (they were pointing to our internal pre-prod servers). It explains why it worked on our side but not on yours. I pushed the fix on Monday but asked for new tests before telling you. On our side the tests are OK. Your issue should be fixed.

**Comment by ganeshmahajan1985** [comment]
Hi, I am still getting the same issue. @jnguiavarch  When do you think it will be fixed?

**Comment by MyScriptSupport** [comment]
Dear Ganesh,

Thank you for your question.
I am puzzled you are still getting the error. Can you clone again your project, proceeding as indicated in the online documentation: https://developer.myscript.com/docs/interactive-ink/1.2/windows/fundamentals/get-started/

Best regards,
Olivier
